apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  extraPortMappings:
  # Kraft
  - containerPort: 32323
    hostPort: 32323
  # Valkey
  - containerPort: 30379
    hostPort: 30379
  # localstack s3
  - containerPort: 31566
    hostPort: 31566
  extraMounts:
  # code coverage for e2e
  - hostPath: build/coverdata
    containerPath: /coverdata
    readOnly: false
